CC = gcc

main: 
	$(CC) main.c console.c game/dinerdash.c game/RNG.c game/stimencarijodoh.c ADT/queueDinerDash.c ADT/arrayGame.c ADT/mesin_kalimat.c ADT/mesin_kar.c ADT/queueGame.c ADT/mesin_input.c -o main

clean:
	rm *.o final