CC = gcc

main: 
	$(CC) -o main main.c console.c game/dinerdash.c game/RNG.c game/stimencarijodoh.c game/snakeonmeteor.c game/TowerOfHanoi.c ADT/queueDinerDash.c ADT/arrayGame.c ADT/mesin_kalimat.c ADT/mesin_kar.c ADT/queueGame.c ADT/mesin_input.c ADT/point.c ADT/linkedlistPoint.c ADT/stackGame.c ADT/stackTOH.c ADT/setGame.c ADT/mapGame.c ADT/datagame.c

clean:
	rm *.o main