CC = gcc

main: 
	$(CC) -o main main.c console.c game/dinerdash.c game/RNG.c game/stimencarijodoh.c ADT/queueDinerDash.c ADT/arrayGame.c ADT/mesin_kalimat.c ADT/mesin_kar.c ADT/queueGame.c ADT/mesin_input.c ADT/point.c ADT/linkedlistPoint.c ADT/stackGame.c ADT/setGame.c ADT/stackGame.c ADT/mapGame.c game/snakeonmeteor.c game/hangman.c

# main: console.o main.o
# 	$(CC) main.o console.o -o main

# main.o: main.c console.o
# 	$(CC) main.c console.o -o

# stimencarijodoh.o

# console.o: arrayGame.o

# arrayGame.o: ADT/arrayGame.c mesin_kalimat.o
# 	$(CC) ADT/arrayGame.c mesin_kalimat.o -c

# mesin_input.o: ADT/mesin_input.c mesin_kar.o
# 	$(CC) ADT/mesin_input.c mesin_kar.o

# mesin_kalimat.o: ADT/mesin_kalimat.c mesin_kar.o
# 	$(CC) ADT/mesin_kalimat.c mesin_kar.o -c

# mesin_kar.o: ADT/mesin_kar.c
# 	$(CC) ADT/mesin_kar.c -c

# queueGame.o: ADT/queuegame.c mesin_kalimat.o
# 	$(CC) ADT/mesin_kar.c

# rng.o: game/rng.c
# 	$(CC) game/rng.c -c





clean:
	rm *.o main